/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2009-8-29, 16:22:29
 */
package biodraft;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JFrame;



import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame implements GroupSetable{

//    public static Connection con;
//    public static String selectedGroup = "root";

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newDataGroupFileChooser = new javax.swing.JFileChooser();
        newGroupNameOptionPane = new javax.swing.JOptionPane();
        frameSplitPane = new javax.swing.JSplitPane();
        topSplitPane = new javax.swing.JSplitPane();
        treeScrollPane = new javax.swing.JScrollPane();
        seqTree = new javax.swing.JTree();
        topRightPanel = new javax.swing.JPanel();
        thresPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pThreSpinner = new javax.swing.JSpinner();
        fThreSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        minSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        maxSpinner = new javax.swing.JSpinner();
        editTogButton = new javax.swing.JToggleButton();
        priemrPanel = new javax.swing.JPanel();
        primerScrollPane = new javax.swing.JScrollPane();
        primerTable = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        selectPrimerPanel = new javax.swing.JPanel();
        customizedRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        forStartSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        forEndSpinner = new javax.swing.JSpinner();
        forPrimerText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        revStartSpinner = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        revEndSpinner = new javax.swing.JSpinner();
        revPrimerText = new javax.swing.JTextField();
        typingPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pathText = new javax.swing.JFormattedTextField();
        fileButton = new javax.swing.JButton();
        typeButton = new javax.swing.JButton();
        resultScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newDataGroupMenuItem = new javax.swing.JMenuItem();
        openDataGroupMenuItem = new javax.swing.JMenuItem();
        deleteDataGroupMenuItem = new javax.swing.JMenuItem();
        newDataBaseMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        treeScrollPane.setMinimumSize(new java.awt.Dimension(35, 35));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        seqTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        seqTree.setRootVisible(false);
        treeScrollPane.setViewportView(seqTree);

        topSplitPane.setLeftComponent(treeScrollPane);

        thresPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Primer Selection Threshold"));

        jLabel1.setText("Min-length of Primer");

        jLabel2.setText("Min-Length of Fragment");

        pThreSpinner.setEnabled(false);

        fThreSpinner.setEnabled(false);

        jLabel3.setText("Length Between Primers  Min");

        minSpinner.setEnabled(false);

        jLabel4.setText("Max");

        maxSpinner.setEnabled(false);

        editTogButton.setText("Edit");
        editTogButton.setEnabled(false);
        editTogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout thresPanelLayout = new javax.swing.GroupLayout(thresPanel);
        thresPanel.setLayout(thresPanelLayout);
        thresPanelLayout.setHorizontalGroup(
            thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fThreSpinner)
                    .addComponent(pThreSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thresPanelLayout.createSequentialGroup()
                        .addComponent(minSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editTogButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        thresPanelLayout.setVerticalGroup(
            thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thresPanelLayout.createSequentialGroup()
                .addGroup(thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pThreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(minSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(maxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(thresPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(thresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fThreSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(thresPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editTogButton)
                        .addContainerGap())))
        );

        priemrPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Primer"));

        primerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        primerScrollPane.setViewportView(primerTable);

        javax.swing.GroupLayout priemrPanelLayout = new javax.swing.GroupLayout(priemrPanel);
        priemrPanel.setLayout(priemrPanelLayout);
        priemrPanelLayout.setHorizontalGroup(
            priemrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
            .addGroup(priemrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(primerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
        );
        priemrPanelLayout.setVerticalGroup(
            priemrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(priemrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(primerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout topRightPanelLayout = new javax.swing.GroupLayout(topRightPanel);
        topRightPanel.setLayout(topRightPanelLayout);
        topRightPanelLayout.setHorizontalGroup(
            topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priemrPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thresPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        topRightPanelLayout.setVerticalGroup(
            topRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priemrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        topSplitPane.setRightComponent(topRightPanel);

        frameSplitPane.setLeftComponent(topSplitPane);

        selectPrimerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Primer"));

        customizedRadioButton.setText("Use Customized Primer");
        customizedRadioButton.setEnabled(false);
        customizedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customizedRadioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Forward Primer:");

        jLabel6.setText("Start:");

        forStartSpinner.setEnabled(false);

        jLabel7.setText("End:");

        forEndSpinner.setEnabled(false);

        forPrimerText.setEditable(false);
        forPrimerText.setText("AGCTTTTTT");

        jLabel8.setText("Reverse Priemr:");

        jLabel9.setText("Start:");

        revStartSpinner.setEnabled(false);

        jLabel10.setText("End:");

        revEndSpinner.setEnabled(false);

        revPrimerText.setEditable(false);
        revPrimerText.setText("AGCTTTTTT");

        javax.swing.GroupLayout selectPrimerPanelLayout = new javax.swing.GroupLayout(selectPrimerPanel);
        selectPrimerPanel.setLayout(selectPrimerPanelLayout);
        selectPrimerPanelLayout.setHorizontalGroup(
            selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectPrimerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectPrimerPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(revPrimerText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(selectPrimerPanelLayout.createSequentialGroup()
                                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(revEndSpinner)
                                    .addComponent(revStartSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))))
                    .addComponent(customizedRadioButton)
                    .addComponent(jLabel5)
                    .addGroup(selectPrimerPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forPrimerText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(selectPrimerPanelLayout.createSequentialGroup()
                                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(forEndSpinner)
                                    .addComponent(forStartSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectPrimerPanelLayout.setVerticalGroup(
            selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectPrimerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customizedRadioButton)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(forStartSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forEndSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forPrimerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(revStartSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectPrimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revEndSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revPrimerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        typingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Typing"));

        jLabel11.setText("Import Mass-Spectrometry Data:");

        pathText.setText("C://");

        fileButton.setText("Open File");

        typeButton.setText("Start Typing");

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultScrollPane.setViewportView(resultTable);

        javax.swing.GroupLayout typingPanelLayout = new javax.swing.GroupLayout(typingPanel);
        typingPanel.setLayout(typingPanelLayout);
        typingPanelLayout.setHorizontalGroup(
            typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, typingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(pathText, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                    .addGroup(typingPanelLayout.createSequentialGroup()
                        .addComponent(fileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeButton)))
                .addContainerGap())
        );
        typingPanelLayout.setVerticalGroup(
            typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typingPanelLayout.createSequentialGroup()
                .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(typingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeButton)
                    .addComponent(fileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectPrimerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectPrimerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        frameSplitPane.setRightComponent(bottomPanel);

        fileMenu.setText("File");

        newDataGroupMenuItem.setText("New Data Group");
        newDataGroupMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDataGroupMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newDataGroupMenuItem);

        openDataGroupMenuItem.setText("Open Data Group");
        openDataGroupMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleOpenMenuItemClicked(evt);
            }
        });
        fileMenu.add(openDataGroupMenuItem);

        deleteDataGroupMenuItem.setText("Delete Data Group");
        deleteDataGroupMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleDeleteMenuClicked(evt);
            }
        });
        fileMenu.add(deleteDataGroupMenuItem);

        newDataBaseMenuItem.setText("Import New Database");
        fileMenu.add(newDataBaseMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//<<<<<<< .mine
    private void newDataGroupMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDataGroupMenuItemActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Fasta files", "fasta");
        newDataGroupFileChooser.setFileFilter(filter);
//        newDataGroupFileChooser.showDialog(null, null);
        int returnVal = newDataGroupFileChooser.showOpenDialog(null);
//        int returnVal = newDataGroupFileChooser.showOpenDialog(parent);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = newDataGroupFileChooser.getSelectedFile();
            String groupName = JOptionPane.showInputDialog("Please input the data group name");
            int groupID;
            try {
                groupID = Controller.createNewDataGroup(file, groupName);
//            if (null != groupName) {
//            }
            } catch (FileNotFoundException ex) {
//                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                ex.getMessage();
            } catch (SQLException ex) {
                if(ex.getErrorCode() == 0x80004005) {

                }
            }

            Controller.refreshTree(seqTree, groupName);
            editTogButton.setEnabled(true);
            customizedRadioButton.setEnabled(true);
//            if (null != groupName) {
//            }
        }
//        newDataGroupFileChooser.setVisible(true);
    }//GEN-LAST:event_newDataGroupMenuItemActionPerformed

    private void handleOpenMenuItemClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleOpenMenuItemClicked
        // TODO add your handling code here:
//        new GroupPanel(this).setVisible(true);
//        new GroupFrame().setVisible(true);
//        GroupFrame frame = new GroupFrame();
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.getButton().setText("Open");
        GroupDialog group = new GroupDialog(this, true, this);
        populateGroupTable(group);
        group.setVisible(true);
    }//GEN-LAST:event_handleOpenMenuItemClicked

    private void handleDeleteMenuClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleDeleteMenuClicked
        // TODO add your handling code here:
//        GroupFrame frame = new GroupFrame();
//        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
//        frame.getButton().setText("Delete");
         GroupDialog group = new GroupDialog(this, true, this);
         populateGroupTable(group);
         group.setVisible(true);
//        this.setTitle(group.getSelectedGroup());
    }//GEN-LAST:event_handleDeleteMenuClicked

    private void editTogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTogButtonActionPerformed
        // TODO add your handling code here:
        if (editTogButton.getText() == "Edit") {
            editTogButton.setText("Finish");
            pThreSpinner.setEnabled(true);
            fThreSpinner.setEnabled(true);
            maxSpinner.setEnabled(true);
            minSpinner.setEnabled(true);
        } else {
            editTogButton.setText("Edit");
            pThreSpinner.setEnabled(false);
            fThreSpinner.setEnabled(false);
            maxSpinner.setEnabled(false);
            minSpinner.setEnabled(false);
            //check the thresholds and search for primer
        }
    }//GEN-LAST:event_editTogButtonActionPerformed

    private void customizedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customizedRadioButtonActionPerformed
        // TODO add your handling code here:
        if (forStartSpinner.isEnabled() == true) {
            forStartSpinner.setEnabled(false);
            forEndSpinner.setEnabled(false);
            revStartSpinner.setEnabled(false);
            revEndSpinner.setEnabled(false);
        } else {
            forStartSpinner.setEnabled(true);
            forEndSpinner.setEnabled(true);
            revStartSpinner.setEnabled(true);
            revEndSpinner.setEnabled(true);
        }
    }//GEN-LAST:event_customizedRadioButtonActionPerformed

    public void populateGroupTable( GroupDialog group) {
        String[] columnNames = {"Data Group Name", "Total number of genes"};
        ArrayList<DataGroup> groupList = DataGroup.getAllGroups();
        Object[][] data = new Object[groupList.size()][2];
        for (int i = 0; i < groupList.size(); i ++) {
            data[i][0] = groupList.get(i).getName();
            data[i][1] = GeneSeq.getGeneNumByGroupName(groupList.get(i).getName());
        }
        group.setTableModel(new MyTableModel(columnNames, data));
    }

    public void setGroup(String name) {
       DefaultMutableTreeNode root = (DefaultMutableTreeNode)seqTree.getModel().getRoot();
       String rootName = root.toString();
       if(name != rootName) {
           Controller.refreshTree(seqTree, name);
           editTogButton.setEnabled(true);
           customizedRadioButton.setEnabled(true);
           DataGroup datagroup = DataGroup.getGroupByName(name);
           pThreSpinner.setValue(datagroup.getLowPrimerLength());
           fThreSpinner.setValue(datagroup.getLowFilterLength());
           maxSpinner.setValue(datagroup.getHighVariableRegionLength());
           minSpinner.setValue(datagroup.getLowVariableRegionLength());
       }
   }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        try {
//            Class.forName("org.sqlite.JDBC");
//            con = DriverManager.getConnection("jdbc:sqlite:BioData.db");
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JRadioButton customizedRadioButton;
    private javax.swing.JMenuItem deleteDataGroupMenuItem;
    private javax.swing.JToggleButton editTogButton;
    private javax.swing.JSpinner fThreSpinner;
    private javax.swing.JButton fileButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JSpinner forEndSpinner;
    private javax.swing.JTextField forPrimerText;
    private javax.swing.JSpinner forStartSpinner;
    private javax.swing.JSplitPane frameSplitPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner maxSpinner;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JSpinner minSpinner;
    private javax.swing.JMenuItem newDataBaseMenuItem;
    private javax.swing.JFileChooser newDataGroupFileChooser;
    private javax.swing.JMenuItem newDataGroupMenuItem;
    private javax.swing.JOptionPane newGroupNameOptionPane;
    private javax.swing.JMenuItem openDataGroupMenuItem;
    private javax.swing.JSpinner pThreSpinner;
    private javax.swing.JFormattedTextField pathText;
    private javax.swing.JPanel priemrPanel;
    private javax.swing.JScrollPane primerScrollPane;
    private javax.swing.JTable primerTable;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JTable resultTable;
    private javax.swing.JSpinner revEndSpinner;
    private javax.swing.JTextField revPrimerText;
    private javax.swing.JSpinner revStartSpinner;
    private javax.swing.JPanel selectPrimerPanel;
    private javax.swing.JTree seqTree;
    private javax.swing.JPanel thresPanel;
    private javax.swing.JPanel topRightPanel;
    private javax.swing.JSplitPane topSplitPane;
    private javax.swing.JScrollPane treeScrollPane;
    private javax.swing.JButton typeButton;
    private javax.swing.JPanel typingPanel;
    // End of variables declaration//GEN-END:variables
}
